In [14]:
from sklearn.cluster import KMeans
import numpy as np
from scipy.spatial.distance import cdist, pdist

In [2]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [3]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int32)

In [4]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

In [5]:
np.array([[1],[1]]).size

2

In [9]:
X2 = np.random.randint(0, 10, X.shape)

In [38]:
X.mean(axis=1)

array([1.5, 2.5, 0.5, 6. , 7. , 5. ])

In [13]:
X+1

array([[ 2,  3],
       [ 2,  5],
       [ 2,  1],
       [11,  3],
       [11,  5],
       [11,  1]])

In [16]:
(X+1) - X

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [20]:
np.linalg.norm((X+1) - X, axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356,
       1.41421356])

In [22]:
print('Input matrix must be a non-empty 2D numpy array where the' \
                            'rows are observations and columns are features')

Input matrix must be a non-empty 2D numpy array where therows are observations and columns are features


In [36]:
X[np.random.choice(X.shape[0], 5, replace=False), :]

array([[10,  2],
       [ 1,  2],
       [ 1,  0],
       [10,  0],
       [10,  4]])